[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid


[program:main]
command=python main.py
directory=%(ENV_PWD)s
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=PORT=10000

[program:main_v5]
command=python main_v5.py
directory=%(ENV_PWD)s
autostart=true
autorestart=true
startretries=3
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
environment=PORT=10001


# Add more programs as needed.
